import { HttpStatus } from '@nestjs/common';

const APPLICATION_ERROR_HTTP_STATUS_MAP: Record<string, number> = {
  INVALID_EMAIL: HttpStatus.BAD_REQUEST,
  INVALID_PASSWORD_HASH: HttpStatus.INTERNAL_SERVER_ERROR,

  USER_ALREADY_EXISTS: HttpStatus.CONFLICT,
  INVALID_CREDENTIALS: HttpStatus.UNAUTHORIZED,
  USER_NOT_FOUND: HttpStatus.NOT_FOUND,

  CONFIG_FILE_NOT_FOUND: HttpStatus.INTERNAL_SERVER_ERROR,
  CONFIG_PARSE_ERROR: HttpStatus.INTERNAL_SERVER_ERROR,
  CONFIG_ROOT_INVALID: HttpStatus.INTERNAL_SERVER_ERROR,
  CONFIG_SECTION_NOT_FOUND: HttpStatus.INTERNAL_SERVER_ERROR,
  CONFIG_KEY_NOT_FOUND: HttpStatus.INTERNAL_SERVER_ERROR,
  CONFIG_VALIDATION_ERROR: HttpStatus.INTERNAL_SERVER_ERROR,

  DATABASE_CONNECTION_FAILED: HttpStatus.INTERNAL_SERVER_ERROR,

  PROJECT_NOT_FOUND: HttpStatus.NOT_FOUND,
  PROJECT_ACCESS_DENIED: HttpStatus.FORBIDDEN,
  PROJECT_ALREADY_EXISTS: HttpStatus.CONFLICT,
  PROJECT_ENDPOINT_NOT_FOUND: HttpStatus.NOT_FOUND,
  PROJECT_ENDPOINT_ALREADY_EXISTS: HttpStatus.CONFLICT,
  PROJECT_ENDPOINT_ROUTE_SHAPE_ALREADY_EXISTS: HttpStatus.CONFLICT,

  INVALID_PROJECT_ID: HttpStatus.BAD_REQUEST,
  INVALID_PROJECT_OWNER_ID: HttpStatus.BAD_REQUEST,
  INVALID_PROJECT_ENDPOINT_ID: HttpStatus.BAD_REQUEST,
  INVALID_PROJECT_NAME: HttpStatus.BAD_REQUEST,
  INVALID_PROJECT_DESCRIPTION: HttpStatus.BAD_REQUEST,
  INVALID_ENDPOINT_METHOD: HttpStatus.BAD_REQUEST,
  INVALID_ENDPOINT_PATH: HttpStatus.BAD_REQUEST,
  INVALID_ENDPOINT_STATUS: HttpStatus.BAD_REQUEST,
  INVALID_UPSTREAM_URL: HttpStatus.BAD_REQUEST,

  API_KEY_ALREADY_EXISTS: HttpStatus.CONFLICT,
  API_KEY_NOT_FOUND: HttpStatus.NOT_FOUND,
  API_KEY_REVOKED: HttpStatus.UNAUTHORIZED,
  API_KEY_ENDPOINT_PERMISSION_ALREADY_EXISTS: HttpStatus.CONFLICT,
  API_KEY_ENDPOINT_PERMISSION_NOT_FOUND: HttpStatus.NOT_FOUND,

  INVALID_API_KEY_ID: HttpStatus.BAD_REQUEST,
  INVALID_API_KEY_PROJECT_ID: HttpStatus.BAD_REQUEST,
  INVALID_API_KEY_PROJECT_ENDPOINT_ID: HttpStatus.BAD_REQUEST,
  INVALID_API_KEY_NAME: HttpStatus.BAD_REQUEST,
  INVALID_API_KEY_PREFIX: HttpStatus.BAD_REQUEST,
  INVALID_API_KEY_HASH: HttpStatus.BAD_REQUEST,
  INVALID_API_KEY_STATUS: HttpStatus.BAD_REQUEST,
  INVALID_API_KEY_ENDPOINT_PERMISSION_ID: HttpStatus.BAD_REQUEST,
  INVALID_ISSUED_API_KEY: HttpStatus.INTERNAL_SERVER_ERROR,

  API_KEY_PROJECT_NOT_ACCESSIBLE: HttpStatus.NOT_FOUND,
  API_KEY_PROJECT_ENDPOINT_NOT_ACCESSIBLE: HttpStatus.NOT_FOUND,
  INVALID_API_KEY_OWNER_ID: HttpStatus.BAD_REQUEST,

  GATEWAY_API_KEY_MISSING: HttpStatus.UNAUTHORIZED,
  GATEWAY_API_KEY_INVALID: HttpStatus.UNAUTHORIZED,
  GATEWAY_API_KEY_REVOKED: HttpStatus.UNAUTHORIZED,
  GATEWAY_ENDPOINT_NOT_FOUND: HttpStatus.NOT_FOUND,
  GATEWAY_ENDPOINT_DISABLED: HttpStatus.FORBIDDEN,
  GATEWAY_ENDPOINT_ACCESS_DENIED: HttpStatus.FORBIDDEN,
  GATEWAY_UPSTREAM_REQUEST_FAILED: HttpStatus.BAD_GATEWAY,

  INVALID_GATEWAY_RAW_API_KEY: HttpStatus.BAD_REQUEST,
  INVALID_GATEWAY_HTTP_METHOD: HttpStatus.BAD_REQUEST,
  INVALID_GATEWAY_REQUEST_PATH: HttpStatus.BAD_REQUEST,
  INVALID_GATEWAY_QUERY_STRING: HttpStatus.BAD_REQUEST,
  INVALID_GATEWAY_UPSTREAM_URL: HttpStatus.BAD_REQUEST,
};

export class ApplicationErrorStatusMapper {
  static toHttpStatus(errorCode: string): number {
    return (
      APPLICATION_ERROR_HTTP_STATUS_MAP[errorCode] ??
      HttpStatus.INTERNAL_SERVER_ERROR
    );
  }
}
