import { HttpStatus } from '@nestjs/common';

const APPLICATION_ERROR_HTTP_STATUS_MAP: Record<string, number> = {
  INVALID_EMAIL: HttpStatus.BAD_REQUEST,
  INVALID_PASSWORD_HASH: HttpStatus.INTERNAL_SERVER_ERROR,

  USER_ALREADY_EXISTS: HttpStatus.CONFLICT,
  INVALID_CREDENTIALS: HttpStatus.UNAUTHORIZED,
  USER_NOT_FOUND: HttpStatus.NOT_FOUND,

  CONFIG_FILE_NOT_FOUND: HttpStatus.INTERNAL_SERVER_ERROR,
  CONFIG_PARSE_ERROR: HttpStatus.INTERNAL_SERVER_ERROR,
  CONFIG_ROOT_INVALID: HttpStatus.INTERNAL_SERVER_ERROR,
  CONFIG_SECTION_NOT_FOUND: HttpStatus.INTERNAL_SERVER_ERROR,
  CONFIG_KEY_NOT_FOUND: HttpStatus.INTERNAL_SERVER_ERROR,
  CONFIG_VALIDATION_ERROR: HttpStatus.INTERNAL_SERVER_ERROR,

  DATABASE_CONNECTION_FAILED: HttpStatus.INTERNAL_SERVER_ERROR,
};

export class ApplicationErrorStatusMapper {
  static toHttpStatus(errorCode: string): number {
    return (
      APPLICATION_ERROR_HTTP_STATUS_MAP[errorCode] ??
      HttpStatus.INTERNAL_SERVER_ERROR
    );
  }
}